module.exports = {
  rules: {
    'react/jsx-curly-spacing': 2,
    'react/jsx-no-duplicate-props': 2,
    'react/jsx-sort-prop-types': 2,
    'react/sort-comp': [2, {
      order: [
        'displayName',
        'propTypes',
        'contextTypes',
        'childContextTypes',
        'mixins',
        'statics',
        'defaultProps',
        'constructor',
        'getDefaultProps',
        'getInitialState',
        'getChildContext',
        'componentWillMount',
        'componentDidMount',
        'componentWillReceiveProps',
        'shouldComponentUpdate',
        'componentWillUpdate',
        'componentDidUpdate',
        'componentWillUnmount',
        'render',
        '/^_render.+$/',
      ],
    }],
  },
};
